### ISSUE TITLE
Add travis support

### ISSUE THREAD

**Issue by eatingzhang0611** [Inventory-Squad/inventory#103]
**As a** developer
**I need** a continuous integration tool
**So that** it is ensured that the service is properly tested. 

**Assumptions:** 
* Using Github
* Using Travis CI as our choice of continuous integration tool

**Acceptance Criteria:**
```
Given I am a developer
When I issue push and pull requests
Then Travis CI should automatically test the code committed.
```

**Comment by faberald** [comment]
We need to link our repo to Travis CI and create a .travis.yml file

**Comment by faberald** [comment]
For  `.travis.yml`

What do we need?

```
language: python
python:
  - "3.6"
  
# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  mariadb: '10.4'

// This is not needed since we use MySQL as the name of DB (which is a bad approach)
before_script:
  - sudo mysql -e 'create database mysql;'

script:
  - nosetests

# require the branch name to be master (note for PRs this is the base branch name)
notifications:
  slack:
    if: branch = master
```
